version: '2'

services:

  api:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo-server

  web-ui:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
    links:
      - api

  mongo-server:
    image: mongo:3.0
    expose:
      - 27017

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web-ui

