import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { APIResponseReviews } from '../shared/models';

const IP = 'http://127.0.0.1:5000';
const API = `${IP}/api/v1`;

@Injectable({
    providedIn: 'root'
})
export class ReviewsService {
    constructor(private http: HttpClient) { }

    fetchReviews(url: string): Observable<APIResponseReviews> {
        return this.http.get<APIResponseReviews>(`${API}/reviews?url=${url}`);
    }

    // fetchReviews(): Observable<APIResponseReviews> {
    //     /* tslint:disable */
    //     return of({
    //         'company': {
    //             'company_logo_url': 'https://media.consumeraffairs.com/files/cache/logos/joe-cooper-ford_logo_10715_widget_logo.png',
    //             'name': 'Joe Cooper Ford'
    //         },
    //         'page': 1,
    //         'reviews': [
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 0,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Oct 3, 2018',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Oki Oki :P...Attention do not buy used vehicles from here. I bought a used F150 from here and 4 months later after taking it to Ford dealership in Tulsa needed transmission replaced that took 5 weeks to finalize everything thru warranty. And motor also needs attention but warranty won\'t cover initial breakdown cost of over 1k until after. I have called Joe Cooper for 3 weeks straight and keep getting passed on with no callbacks. They were eager to call back and negotiate to sale but not eager to rectify the situation. All I asked was for them to look at covering initial cost to check for problem in motor. That would more than likely be covered by warranty. I still have not spoken to a manager.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Broken Arrow, OK',
    //                     'image_url': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_463226_head_shot_tiny.jpg',
    //                     'is_verified_buyer': true,
    //                     'is_verified_reviewer': true,
    //                     'name': 'MrCoachberry23'
    //                 },
    //                 'reviewer_image': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_463226_head_shot_tiny.jpg',
    //                 'stars': 1.0,
    //                 'verified_buyer': true,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 0,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'May 23, 2018',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Three years ago we purchased two vehicles from Joe Cooper Ford \u2013talking about \u201chassle-free\u201d heck yeah! Luis **, Mgr was attentive, professional, not pushing, good listener. Three years later we received nothing but the same as the the first time -this time a salesperson named Andrea ** was magic to us. She worked with my wife\'s and I schedules for over a month. She never was trying to \'make the sale\'. She was always trying to help us and guess what; she did it! We purchased not one but two vehicles again because of her professionalism, good listener, attentive, and patience. THANK YOU ANDREA. YOU ARE AWESOME!',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Yukon, OK',
    //                     'image_url': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_395560_head_shot_tiny.jpg',
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Americo'
    //                 },
    //                 'reviewer_image': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_395560_head_shot_tiny.jpg',
    //                 'stars': 5.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 0,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'March 17, 2018',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I found a Truck on Joe Cooper Ford Edmond website that I was interested in. It had a price of 37,777 on website. I went by the dealership that weekend and looked at the truck and it had a price of 36k on the windshield. I sent an email through their website asking for the correct price. The next day the salesperson, Choyah ** emailed me sending me a walk around video of the Truck and asking when I would be in. I emailed Mr. ** back stating I had little time and wanted to know which price was correct. I then advised I would be interested in the truck for 32,500.00. A short time later Mr. ** emailed saying he had talked to his manager and was told to sell the truck at 32,888.00 which included doc fee. He asked if we had a deal? I advised I would come and drive it and do the paperwork. Mr. ** continued to email me and text asking when I was coming in and he was saving the truck for me at 32,888.\nI made it to the dealership after a 45 minute drive and met with Mr. **. We drove the truck and went inside to do the paperwork. I filled out the paperwork and Mr. ** took my license and made a copy. He then took my paperwork and said he would be right back. Twenty minutes went by and I stood up to see where Mr. ** went. He saw me and advised they were finishing up and it would be a couple of more minutes. After sitting and waiting for an hour, Mike ** comes up and introduces himself. Mr. ** then advises \'we have a problem with the truck\'. He goes on to tell me that I had seen an out of date ad and then he had over 39,000.00 in the truck and could not sell it to me for the price he advised. He then stated he would sell it for 37,777.00 (the exact price on the ad). Now for one the ad I saw was not old and two why would it matter what ad I had seen.\nI made an offer and they countered which I accepted. Has absolutely nothing to do with an ad. Just a new twist on the bait and switch. So I left quite upset that they had not only lied to me but they had wasted my time and gas. I took the afternoon off to buy the truck so I lost that time at work as well. On my way home Mr. ** and I exchange a few emails where he backtracks stating I looked at a bad ad and it wasn\'t their fault. Now how is them sending me a price they will sell the vehicle at and backing out not their fault. So I ask him to quit insulting my intelligence and stop texting. Story should be over but no. I get home and check my email. I have an email from Mr. ** thanking me for my time and advising he is including additional information on the Truck. It was the same ad I responded to in the first place.\nI also received a voicemail from the General Manager, Daniel **. Mr. ** asked me to call him. I did call him just to see what he would say. Mr. ** again starts telling me I saw an incorrect ad on the truck and the truck was 37,777. I stopped Mr. ** and advised him I did not see an incorrect ad and that was the price his salesman and I started at. I then stated that it didn\'t matter about what ad I saw; they were the ones that offered me the truck at 32,888.00. Mr. ** advises he cannot come close to that price. I ask why they quoted me that price to which he stated \'I don\'t know\'. Classic bait and switch. Mr. ** then says he will sell me the truck \'right now\' for 37,000.00 and a free tank of gas. I advised Mr. ** he should sell me the truck for the 32,888 which I have in an email showing that price. I also advise they cost me time money and gas to get me in the dealership knowing they weren\'t going to stand behind the price they quoted me.\nI also asked why they had me sit there for an hour if they knew they weren\'t going to sell me the truck for the 32,888. Again he replied \'I don\'t know\' I offered to send him all the emails showing my exchange with Mr. **. He said he didn\'t want them but I could stop by anytime and he would fill up my gas tank. So that shows how disrespectful they are of other people\'s time. Looking at most of the other reviews on this site it appears they do not care about the customer any longer. They just want the quick sale. Absolutely the worst situation I have ever dealt with buying a vehicle. All I can say is get your price in writing. Oh wait I did have my price in an email and they still set me up hook line and sinker.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Mustang, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Tom'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 0,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'March 17, 2018',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Went to JC Ford (Shawnee, OK) to purchase a 4-wheel drive pickup. Salesman (Jim **) showed me several pickups and I chose one off the lot. After a price was agreed upon started with filling out the paperwork for purchase. During the signing of the papers I asked more than once if the truck was a 4-wheel. Salesman assured me that it was. On final signing I asked once again if this was a 4-wheel truck. I was assured by salesman that it was. The next day after returning do more finalization of the purchase my wife and I returned home and started transferring our insurance from my trade-in F150 and my wife noticed on paperwork that she did not believe this was a 4-wheel truck. I got out the handbook and looked for instructions on how to engage into 4-wheel mode as I was unfamiliar with electronic engaging. I became livid at the fact that this was in fact, not 4-wheel drive.\nImmediately I called Jim ** and was livid with my explanation that this was not a 4-wheel drive and was considering returning and getting my old truck and truck back and the cash that was paid. My wife and I had conversations with another salesman (Garrett) that was involved and was making our complaint. She had heard him over the phone call Jim ** and asked him about our complaint and she overheard him say that he did tell me it was a 4-wheel truck. She informed Garrett that I had been suffering from the flu and could not come to JC Ford and Garret agreed because he had a 6-month-old child at home.\nI had at some point talked to Garret over the phone and said that there was a steering and suspension problem with the truck and would agree to keep the truck if the problem was solved and fixed. He said that he would bring it to, I guess upper management, and maybe something could be worked out. At some point down the line I was informed to bring the truck in and they would \'fix\' the truck. I did bring the truck back and it was taken to their mechanic and the alignment of suspension was checked out. The truck was released to me and I started driving my truck home and the problem was not fixed as it was still pulling radically to the left as I had described to the salesman before.\nAt returning the truck was once again taken to the mechanic and again was brought to me as fixed. Also, the mechanics rotated the tires as they said this was the problem. The \'maintenance\' supervisor (I guess) asked if I wanted to take the truck or did I want to take it for a test drive. I told him I trusted him the last time that it was fixed and l wanted to test drive the truck. I had gone less than 1/4 of a mile and the truck was still pulling radically to the left. I was asked if it was better and I informed him that I did not want it better \'I wanted it right\'.\nI was taken back to the dealership and was taken to an office and a Sales Manager came and after shortly going the sales process he informed me that all had been done to resolve situation. I informed him that I had purchased the truck \'as is\' and that there was nothing else they could (or would) do. I informed him that the truck was misrepresented as a 4-wheel and I wanted my truck and money back. That was not going to happen.\nAs I was walking out I returned to Jim ** office space and asked him if he indeed informed me that it was a 4-wheel drive. He denied the statement. In my anger I told him to get his \'lies\' straight. Briefly talking to my wife we decided to let the matter lie for the moment as we have been in court the past few years with settlements and was on the winning side each time but we did not want to be in litigation for an extended period of time again. I do want to inform you of this situation and if there is anything that can be done to resolve this with some satisfaction on both sides. If you need anything else I can be contacted also at ** or **. Thank you for your time, I hope to be hearing from you.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Shawnee, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Pat'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 3,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Nov 22, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Our salesman showed us paperwork reflecting $2100 for my trade-in. I told him we were way off base and thanked him for his time. He asked me about how much I wanted as a monthly payment and said he\u2019d see what he could do. He came back with another offer that appeared to give me $4000 for my trade in. What happened was they increased the price of the vehicle to where they were basically giving me what they originally offered. By the time I caught onto what happened, the paperwork was done. I had the choice of backing out and taking a major hit to my credit or going through with it. I chose the latter. I\u2019ve regretted my decision to purchase from them since the day it happened, and I\u2019ve learned a hard lesson.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Elk City, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Beth'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 3,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Oct 28, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Recently I had an airbag light come on. I took it to Joe Cooper Ford in Yukon where I had purchased the vehicle. After waiting 3 1/2 hours for them to diagnose the problem, I was advised that the problem was with the seatbelt on the passenger side. The service technician advised me that the passenger side seatbelt pretension reel system would have to be replaced. He advised that the cost for replacing the mechanism was going to be nearly $800 and that it was not covered under the extended warranty I had purchased. (Don\'t waste your money on extended warranties!)\nI chose to take the vehicle to a different mechanic because the warranty did not cover the problem and I felt that the price was inflated. The mechanic ordered the part that Joe Cooper\'s technician said I needed. After the part was replaced, the problem still existed. This is when I discovered that Joe Cooper\'s technician misdiagnosed the problem. After spending money and time for them to misdiagnose the problem, I was advised by the other mechanic that it was only a corroded ground wire and it would only cost $100 to repair. If I would have stayed with Joe Cooper\'s diagnosis, I would have spent the $800 and it still would not have been fixed. Basically, I will not return to Joe Cooper for service, repairs, or future purchases.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Oklahoma City, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Remo'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 5,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Sept 28, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I purchased a used car from Joe Cooper in Shawnee late last week and that very same night the CEL came on and the car began to lose power. I scanned the code with a code reader and noted P2144 error - referencing the EGR valve and solenoid. I cleared the error and tried to replicate it. It was literally the 3rd time I started the car. Once on the test drive, second to drive it home, and then later that night... Check Engine. I was told during the sales pitch that many things had been done for maintenance on the vehicle to make it ready for sale, including new tires, brakes, shocks, and a thorough standard inspection.\nThe following Monday I was headed to Shawnee and then to the dealership to discuss the issue when my car died just off Hwy 177. I lost power steering and braking. It would not restart. With my code reader fortunately still in my car, I was able to get three codes setting off my CEL at that time, and again they were all EGR-related. My engine would not remain on after starting. Eventually they agreed to tow my car to the new dealership on Interstate drive and said they would cover a diagnostic of the car. 2 hours after being stranded I arrived with a family member and my useless new-to-me car on a tow truck at the dealership 3 miles away. The service dept (by this time I had dealt with 3 separate service techs) said they would diagnose my car the following day.\nThe next day TJ called at 2 pm to report they were still trying to figure out the problem, that removing the cover to the air filter they found \'dog food and evidence of a rodent infestation.\' (How this was overlooked during their routine maintenance check of the car escapes me as PittStop or any oil change center would find an issue as ridiculous as animals setting up residence against and around my air filter - and considering the issue began the first night I can only assume they were there when I bought the car.) I was told that after cleaning the infestation they were getting new error codes and trying to see if any wires were affected.\nI called back at 4:45 that day after hearing nothing and spoke with Randi who told me that the technician had determined my fuel pump was bad and it would cost $1018 to fix and that I bought the car \'as is\' and I was responsible for the repair. I noted I never got a computer code related to the fuel pump on my computer reader and asked what code the tech received that lead to that conclusion. That information was not available. Somehow after asking for this information some sort of manager was brought into the situation and my repair cost magically fell to $780.\nI spoke to my own mechanic. He asked for the result of the fuel pressure test, stating that it would be suspect to think a fuel pump would be faulty or cause issues with the EGR system without verifying there was no pressure in the fuel lines. I called Joe Cooper back and Randi told me she would be happy to have a \'2nd opinion\' tech take a look at my car. She could not provide me with the error codes presented or the results of a fuel pressure test. I asked if they could do that test or share the results with me because I had never read a code from the car\'s computer that was related directly to the fuel pump, and I was concerned that I was being asked to approve an $800 replacement of a car part that may not actually be the problem.\nThe next day no one contacted me from Joe Cooper. I called and talked to Randi around noon and was told that the previous night they could not locate the keys to my car and the next morning the original mechanic admitted to having locked them in his toolbox overnight. He told her voltage was low and that resulted in his fuel pump diagnosis. I asked for the fuel pressure test and a check of the mass airflow sensor be performed. She agreed and said she would get me the codes the car was showing and call back. It never happened. I am still carless. I missed 2 Dr appts that were scheduled 4 mos in advance. They are adamant that I pay for any repairs despite immediate problems with the car. Guess I will try again tomorrow.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Shawnee, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Ricky'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 15,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'July 19, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'For an audio review and to see how they treat their customers check out the one I\'ve done here: **. I was in the market for a new truck (2017) and decided to give Joe Cooper Ford of Edmond a shot. They didn\'t have what I was looking for (8\' long bed). The salesman directed me toward a used one instead. I liked it well enough and we ran some numbers. They told me they could get me 2.99% APR and I agreed (after going home and doing some research on the truck). I returned later the day to buy the truck and that is when the problem started.\nAfter waiting around for about 3 hours in the lobby I was finally taken back to the finance office (at this point it was about 9pm, an hour after closing). The finance guy seemed irked I wanted to read through the contracts (since he was already staying late) but it was a good thing I did. Suddenly I was up to 3.64% APR, considerably higher than I was previously told. When I asked about this he got annoyed and essentially said I was never given 2.99%, but fortunately I had proof (the paper I was given earlier in the day). So the main finance guy and the other 2 team members still there went back into the office and made me wait outside while they talked. Unfortunately the office has paper thin walls and I could easily hear them bad mouthing me and threatening to make me walk home (I had gotten a ride up to Edmond in anticipation of getting a new vehicle). \'Make his ass walk home.\' \'Call his bluff. He\'ll come back tomorrow.\'\nEventually the main guy agreed to the \'eat the cost\' of the difference since I had the paperwork showing what I was told earlier. But then I noticed the odometer statement ALSO wasn\'t correct. I went outside to get the correct number and when I was returning I was informed by the salesman that they would NOT honor the agreement about \'eating the cost\' and that I would need to find my own creditor. The day ended on a bad note with me being stranded in Edmond for 2 hours at 10:30 at night waiting for a ride home. The next day was even worse. I was called early by the original salesman who apologized for the night before and asked if I\'d come back in if he gave me the 2.99% (we originally agreed on) as well as $50 cash. I decided to be the bigger man and agreed. So I get a ride up there... AGAIN. Only this time I take the precaution of recording everything from the moment I step in the door.\nI STILL decide to try and stick it out at which point he gets eerily calm. He reads the paperwork for a bit before telling me to shut off my recorder. I refuse, informing him Oklahoma is a \'One Party Consent State\' (only one person has to agree to being recorded, ie. me). He then gets EXTREMELY agitated at wanting to be held accountable for what he says. He refuses to continue the transaction unless I shut off my phone, which I finally agree to. Oh yeah, they also reneged on the $50 cash back despite having that recorded too. Liars and crooks who will say anything to make a sale.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Midwest City, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Robbie'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 13,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'June 30, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'My family and I have purchased many vehicles over the years and never experienced anything like we have from Joe Cooper Ford in Shawnee. During the purchase, the staff and management were very excited to assist us. We drove a few used vehicles and then decided on a Cadillac SUV from the Cadillac lot. The test drive seemed to go well but it was getting late and we had to get back to McAlester. We realized that we never backed the vehicle during the test drive but figured the SUV had a backup camera. Before the trip back to Shawnee, I spoke with one of the managers named Ray to ask if the Cadillac had backup camera. I explained that my wife would not like to purchase if it did not have the camera. He assured me that it did and we signed the paperwork that evening.\nSince I was told that the SUV had a camera, I didn\'t feel the need to verify when we arrived at the lot. We spent a lot of time with the finance manager as he continued to talk us into purchasing the extended warranty. He basically made it sound as if the Cadillac would eventually fall apart and each part was so expensive. I gave in and purchased the expensive warranty. As my wife was ready to drive the new purchase back to our home she realized the SUV did in fact not have the backup camera. That night I sent Ray an email stating I would like to cancel the purchase and bring the car back. He told me the following day that we could bring it back and find another. Then the story changed and we would have to wait a few weeks. This continued for a week and was even promised (via word of mouth) that the lot would install a camera. I continued to send messages but was ignored by management, staff, and the finance manager.\nYesterday I sent a message asking for the owners POC, and was contacted by two different managers. One manager named Mark, sounded as if he truly cared about the situation. I explained that it is illegal to tell a customer a vehicle has something when in fact it does not. I understand that salesman use \'puffing\' to make a vehicle sound better, but they can\'t say it has something that it doesn\'t. I was told that the lot would install the camera, but received a different response yesterday from the GM named Bill. He sent an email stating that he looked up the documents and did not see anything showing that they owed me anything. Really!!!\nI am not done with this situation and will not stop fighting until I receive what was promised. Another fact I forgot to mention is the lot had the vehicle listed for $20,500 and somehow I ended up paying $23k before the extended warranty. None of them can explain that either. Take your hard earned money to a dealership that actually cares about people, not one that is out to take advantage. We didn\'t even need the car as it was a third vehicle and yet they still managed to screw us over. The response I received from Bill yesterday really upset me even more than I already was. Did I mention that after I sent a response to him, he ignored me. This is common practice and the owner should step in and take control of his employees.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Hartshorne, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'Brian'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 9,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'May 16, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I went in had $100.00 to my name and I needed something so I could get my kids to and from school and me to and from work. Well because I have to have a job to provide a reliable transportation to get to work so that I can provide a comfortable living. I was satisfied with the salesman and the opportunity to have gotten put into a car with very little down. What I\'m not satisfied with is that after having the car less than a month even making my first payment the car gives me problems and things I know I shouldn\'t have to pay for. I know it\'s as is but this car lot was not at all concerned about the issue I had with the vehicle. And they are supposed to have it towed and I\'m out of a vehicle and I\'m not so sure when I call back in the morning if I will have the answer I\'m looking for. I asked if I could at least see about a loaner or even just another car altogether seeing is how the car salesman William had already had this car picked out for me.\nI test drove it. It drove well but not for very long. I feel like he took advantage of my unfortunate situation and he\'s even still kind of a jerk, wasn\'t trying to say I understand or anything. Just made me sound like I was a complete idiot. I find this very wrong. They aren\'t in any hurry getting anything done but when it comes to making the payments they expect you to be right on top of that. This is seriously pissing me off the more I think about how after having worked hard all day I get in my vehicle expecting to pick my husband up from work and going home instead having to pull over a more than a few times because it felt like the axle was fixing to break.\nI would say overall they are all about first impressions and after that they really are careless. I wish there was a way out of this and I can take 500 down to a better lot where I know they take care of their customers. Because Joe Cooper easy credit auto is just not the lot to go to. I will be looking further into this and it really pisses me off how they underestimate my intelligence like I\'m completely clueless. Not happy at all. Especially after seeing some of the reviews on here. Also while waiting on the vehicle my first day my salesman asked me to go to a link he messaged me, asked me to say something nice about him and also about the guy who referred me. I really hate that I trusted William as much as I had because if I would have went to a different salesman and I wish I had then. I\'m sure I would have been satisfied. But this guy talks to me like I\'m an idiot. At one point I was just so frustrated I gave the phone to my husband.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Oklahoma City, OK',
    //                     'image_url': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_233724_head_shot_tiny.jpg',
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Monica'
    //                 },
    //                 'reviewer_image': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_233724_head_shot_tiny.jpg',
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 5,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'May 9, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I got a truck in Shawnee in December and I\'m been having trouble with it and it costing me a lot money on repair one right after another and I spent all my money on repairs. I wishes that you can have it fix without cost to me for once.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Mcloud, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Rocky'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 7,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Feb 3, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I took an F-250 pickup in for a warranty replacement of a water pump. Three days later have not heard a word from anybody at Joe Cooper Ford and the service manager, his secretary, fleet manager are all unable to return a telephone call after repeated attempts to reach anyone. I will not be taking any more vehicles to Joe Cooper for service nor will I buy another vehicle from them. Worst service bunch I have ever dealt with.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Skiatook, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Joel'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 11,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'Jan 24, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Wish I could rate Joe Cooper 0 stars! Joe Cooper sold me a F150 and I\'ve always been told don\'t buy the extended warranty but I did buy the drive train extended warranty because Charles the salesman talked me into it and made me feel good about having peace of mind about buying a used truck. I should\'ve know he was lying because his lips were moving typical car salesman tactics just to make the sale!\nAfter 1 year the transmission started leaking and guess what seal and gaskets aren\'t covered in the extended drive train warranty. Ford issued a TSB (technical service bulletin) in 2011 because this is a known common problem. My family has bought 8 cars and trucks from Joe Cooper but this F150 is the last vehicle that Joe Cooper will sell to our family and we will be taking our business elsewhere. I hope the $632 to fix the transmission leak not covered in the drive train extended warranty was worth losing our family\'s business!? Go to Bill Knight or another dealership in the area because you receive HONEST and BETTER service anywhere else!',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Broken Arrow, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'Chris'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 10,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Jan 7, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Me and my husband have been basically lied to. The first time we test drove a vehicle liked it but we need more down payment. Told them it would be a couple of weeks before we could get it. They called and emailed us constantly about purchasing the truck. My husband called them on Friday said it would be Monday before we had the money. He said it was fine. Truck would be there for us Monday. Monday came they sold the truck on sat without even contacting us to see if we were still interested and wanted to come put a check to hold. Friday the 30th of Dec we went in. (This is after my husband called about a second truck he seen on a Sunday and they told us it wasn\'t for sale and when we showed up this day it was on the lot for sale. That should have been the first Red flag.)\nWe drove a couple of vehicles and I found one I liked but it made a grinding noise in the front end and it had the original tires on it (need 4 new ones). They told us what our payments was and said they would do anything to fix the problems we addressed. So we left. Today rather this morning 6th of Jan the general manager called us to find out what the problem was why we hadn\'t purchased a vehicle yet. I explained my circumstances and he said he would find me what I needed and call me back. By 2 we made plans for the night in Tulsa (2 hours away). While in Tulsa we stop by one of their locations to see what they had and they didn\'t have nothing.\nMy husband said to call the GM back so I did. Mind you we had plans already made. But he told me to come in to the Yukon location and they would hold 2 vehicles for me to choose. The one I had test drove (he said he would put 4 new tires, fix the noise and anything else we needed on this one) or I could test drive a newer model. We cancelled plans and drove over 2 hours to do what we needed and when we arrived they had sold one of the vehicles out from under us again. Then tried to give me some lame excuse. I have a bad taste in my mouth and will not purchase from them. Makes me not want to purchase for anybody now, cause my trust for car dealers is gone.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Blanchard, OK',
    //                     'image_url': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_188921_head_shot_tiny.jpg',
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Tamaria'
    //                 },
    //                 'reviewer_image': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_188921_head_shot_tiny.jpg',
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 6,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Jan 3, 2017',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I had an appointment for Saturday at 8:30 in the morning. I came in and brought my Mustang into forward, they were asked to do the relearn position for the misfiring monitoring system on my car after I had to replace my clutch and flywheel. They were not able to do this service at the time with the technicians that they had on hand. So then the service rep calls his main guy on a Saturday on his day off and ask him if it was a procedure they were able to do? Technician quoted \'yes it\'s something they can do there as long as they\'re able to read a book which I don\'t think they can but I\'ll be in on Monday.\' So we rescheduled for Monday.\nI bring the car in on Monday at 8:30 to have the technician work on it. 2 hours later as I\'m waiting I got a question of do I have a tune on my vehicle. I stated \'yes I have a 93 octane tune on the car.\' He said \'okay I\'ll tell the tech.\' Then comes back an hour later and says \'I need to take you out here so that I can explain what\'s going on.\' So then he takes her to the technician the technician then says he\'s been trying to reflash my PCM comma and was unable to communicate with it properly. So then he says he tried to manually program my PCM the way that he said that he read the book said it should three and it did without fail. Then he said my PCM is no longer communicating with my car and I\'m going to need to buy another one which will cost $1,100. My problem is my car ran fine getting there. it had a code for misfiring now my car doesn\'t run and they\'re telling me I need to install $1,100 part that they\'ll cover the labor for.\nThis is BS. I am a service manager for a major retail company for automotive and I know that if we make a mistake we do not charge the customer for their mistake we made on accident. I also understand mistakes happen and this is fine but you did not charge $1,100 for a part that you broke. Now it\'s only going to take four more days for it to get shipped in and I\'m going to have to cost out of my pocket for $1,100. This is wrong and needs to be corrected--the whole procedure, the way that they took him handle this for the technician trying to do it on his own and breaking it was incorrect. So hopefully this can get some results from the way that they run their service managing and the way that they run their technicians there they don\'t think of each other already they talk bad of each other apparently when they\'re not know when they\'re on speakerphone. So please contact me back in this manner thank you.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Edmond, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': true,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Dewain'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': true,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 10,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Oct 23, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Unfortunately Joe Cooper Ford of Shawnee exhibited everything that is bad about the car buying business. I drove a considerable way to test drive and pick up an Escape they had listed and I wanted. I test drove the vehicle and agreed to buy it. Shame on me. I wasn\u2019t feeling too well and just wanted to wrap up the purchase and go home. Several services were added to my contract without my consent and without explanation. I called after I got home and reviewed the contract. I got a hold of someone that said they would get the charges reversed and it would take up to 2 months for all the paperwork to be corrected and funds credited.\nAfter the two months, I did not receive any confirmation and attempted to get a hold of the gentleman who said he was helping. No surprise he is gone and when I finally and directed to someone who actually could help me who by the way did not work at the dealership and was the only who could have helped me all along. I am not sure why I wasn\u2019t directed to her in the first place. After 6 months I finally got the process to conclusion but also losing a considerable amount of the value of those canceled services. My only conclusion is either the employees at Joe Cooper Ford of Shawnee are inept or are deceptive in their practices. Either way I would avoid them like the plague.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Lawrence, KS',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Bill'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 9,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Sept 26, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'We bought a 2013 Ford Focus for my daughter for graduation so she would have something reliable. That is not the case!! It has been in the shop 3 times since we have had it (All for transmission issues). My daughter is not old enough to get a rental car from them so myself or my husband has to take off work to go get it or take it back. I wish they would have told us that kind of car has transmission issues before we bought it!! Would not recommend Joe Cooper to anyone!!',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Hominy, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Christina'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 9,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'Aug 18, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I recently purchased a used vehicle from Joe Cooper last May. I thought the salesman I dealt with was honest and great. Well two weeks after I drove off the lot, my car started to overheat. Joe Cooper approved me to take my car into a service shop closer to where I live being that the road side assistance is only free for 25 miles and well I live over 200 miles away. They fixed the original problems with no hassle. Mind you, I noticed that the car still wasn\'t driving right, but I thought I just need to have all my fluids changed since it had overheated. I had that taken care of thinking that the car would drive better and it only got worse.\nI called Joe Cooper service and they agreed again to take the car back to the service shop to determine what\'s going on. My car has been at the service shop for a week now. The service manager finally after 4 days, calls me to tell me that the problem with the car is not going to be covered under warranty, it is going to be $1000.00 to fix the car and that they want me to pay $250 down and an extra $75 on my car payments which I am current on. I can understand things not being covered under warranty, but I cant understand why they do not want to work with a good customer who has had problems with this car since I bought it. Even the guy at the service shop said that you can tell this car has had problems for a long time and asked me if Joe Cooper even serviced the car before I bought it? I brought that up to the service manager and he just laughed it off.\nAs a single Mom whom lives far out from anywhere, it is very important for me to have reliable transportation. I wonder if I was his Mom, wife, Daughter, and or even sister, would he be laughing then. It should not be so difficult to work with your customers that need help fixing the crap that you sold to them. I will never ever refer anyone to the dealership. Not only for the crappy cars, but for their poor customer service and lack of respect.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Calvin, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'Juanita'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 7,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'July 30, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I have purchased two cars from Joe Cooper Easy Credit over the last few years and I understand that they are helping us to reestablish our credit when we have had problems in the past. Yet, this last vehicle I purchased, I have made payments on it for almost two years and have not been late or missed a payment. Today, I went in to see about trading in my vehicle for a small pickup. After filling out paperwork and waiting for some time, I was informed that my vehicle had too many miles on it for them to purchase it back.\nIf I wanted to give them an additional $1000 and my vehicle then they could help me out. Or I could wait for four more months and then come back and try again. I explained to the salesman that I have already paid almost $9600 in two years for this vehicle and that was more than the vehicle was worth then and that Joe Cooper had already made their money on this vehicle, besides the extra that they were wanting now. He told me that he understood and that I was approved for another vehicle, so if I would like to go ahead and purchase the small pickup, I could just pay for both vehicles.\nIt would seem that if you have a customer that has been loyal in making payments and is wanting to return to do more business that you would accommodate them. When you have already made money on this purchase and then are trying to get more... that is bad business. I don\'t care how bad it gets in the future... I will not be back to Joe Cooper\'s Easy Credit!',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Perry, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Tim'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 2,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'July 21, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'My car has been in for service for the same front end issue 4 times, 2 of which required them to keep it for a week each time. 2 weeks ago the issue began again and instead of bringing my car in I wanted to discuss the problem with the Service Department Supervisor. After numerous attempts and finally an email to the manager I received a call back from the Service Department Supervisor but unfortunately I was unable to answer the phone when he called. Now 9 days later and many phone calls and another email I have yet to speak with anyone about my car. This is beyond frustrating. I want to stay with Joe Cooper for convenience and because they have the records as to what has been done on the front end but I am beginning to think I need to change to Bob Hurley Ford.\nI have been a customer with Joe Cooper Ford since they purchased the Ford Dealership on 34th and Sheridan. Since 2002 I have used the Ford Dealership at this location for all service needed on my Ford vehicles. In July of 2013 I purchased a NEW Ford Explorer Limited from Joe Cooper. Within a week I had an issue and brought the car in for service. I expressed my disappointment to the advisor and I was told \'We don\'t make the cars. We just fix them\'. Over the past 3 years I have experienced some of the worst customer service from the Service Department. It is extremely difficult to get in touch with your service advisor for updates, at times they can be dismissive and rude and my car almost always comes back dirtier than I left it.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Tulsa, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Tracy'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 10,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'July 14, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Over the past 14 years my wife and I have owned about 13 vehicles. It doesn\'t take a math professor to do this simple math; a new car almost every year which means we are trading in a one or the other every 2 years. So we know and have seen quite a bit of the car buying experience. Joe Cooper Ford has to rank among one of the worst places we have EVER been to purchase a car. We were there last Saturday (drove over an hour and half to Tulsa) to look at trucks. We knew what we wanted in a vehicle, and we know what we should have received on our trade in. The sales person took our information and ran the numbers and came back at us with a ridiculous payment that wasn\'t even in the ball park of where we wanted to be.\nHere is where it gets interesting, he didn\'t even want to try and work to get us in a vehicle!! I told him what he was trying to give us on trade in and monthly payment was ** and essentially he told us that if we wanted to be in the price range we wanted to be then we were \'barking up the wrong tree!!\' LMAO! Really?? Well mind you Joe Cooper of Tulsa we did find us a truck and purchased it the same day (when we find what we want we are serious car buyers!!) IF YOU ARE LOOKING FOR A GOOD SALES EXPERIENCE THEN GO TO EVERETT CHEVROLET IN SPRINGDALE AR!!! They know how to truly treat a customer and work with you to find what you want and the price point you are looking for. If I was the owner of this car dealership I would seriously evaluate the management and sales staff that worked for me.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Miami, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'Travis'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 2,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'July 1, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I took my 2011 Escape in for service because my power steering would randomly stop functioning. I was told that the torque sensor had gone out. After looking online I found out that 1.1 million Escapes had been recalled because of faulty sensors, but mine was not in the correct batch. The repair was $742.00. I contacted Ford Motor Corporation and explained the issue. Ford in turn did contact Joe Cooper. Although my part wasn\'t in the recall, they were able to pay half of the bill. My part was only $321. Not a perfect outcome, but much better than the first option.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Skiatook, OK',
    //                     'image_url': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_124846_head_shot_tiny.jpg',
    //                     'is_verified_buyer': true,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Debra'
    //                 },
    //                 'reviewer_image': 'https://media.consumeraffairs.com/files/cache/profile-photos/photo_124846_head_shot_tiny.jpg',
    //                 'stars': 4.0,
    //                 'verified_buyer': true,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 2,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'May 27, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Todd was absolutely AMAZING!!! I have never went in a car dealership and gotten out so fast with a car I loved! I live almost 2 hours from the dealership so he made sure everything was handled before I got there!! I would recommend him to anyone!!',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Canadian, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Allison'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 5.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 5,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'May 1, 2016',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I have never been treated this badly by a dealership. The salesman Ryan was very nice but he lost a sale over $300 because the managers wouldn\'t budge on the price of a used Mustang. Their General Manager I believe his name was Don, but if that\'s wrong then he was the short, fat, bald guy with glasses. I explained how many times I\'d been there and what I was willing to pay based on other dealers and mileage of similar vehicles and he had the nerve to tell that \'maybe you just shouldn\'t buy a car here\'. (Not the only remarks he made, he also defended his pricing and the negative reviews that this dealer has, as well as continually cutting me off as I spoke and escalating his negative tone.)\nSo anyway he took it to a personal level very quickly and I\'d had enough and told him that I could accommodate him and buy elsewhere. But I kept my cool and said to have a nice day. He smirked and made the same statement only in a childish condescending tone and had the nerve to march up to my face as he said it and then followed right on my heels as I left his office and was chasing me out the door when I stopped. That\'s when I could no longer tolerate this jerk and I advised him to back up immediately. Apparently he could tell I was serious and he backed up. Who does that??? Who insults people and then continues to argue as I tell them I\'m leaving?\nI was warned about this dealership by so many people but I gave them a shot because they are in my hometown. I will never set foot on any Joe Cooper lot again. The management here is the worst I\'ve ever seen. They do not come off their prices at all. The GM is lucky I\'m as patient as I am because anybody else would have knocked him out if he had spoken and acted that way and he came very close to that happening. Thank goodness I possess the manners and restraint that this jerk doesn\'t have. He\'s in the only business that would have this kind of fool working with them. To the salesman Ryan **, I actually feel bad and any other dealer would be lucky to have a young man like this working for them. So give him a call and hire him away from this awful place.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Del City, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Jet'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': 'Oct 3, 2015',
    //                 'customer_response_text': 'As of a few days ago, they contacted me and said that they would give me a parts refund due to them losing my parts.  I can\'t tell you how much I am relieved.  I was scared at first because they wouldn\'t call me, but in the end it all worked out.  Again,  the car was fixed well in the first place.  I am happy for their help and I change my rating because they were kind and gave me a parts refund.',
    //                 'helpful': 3,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Sept 25, 2015',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I have been working with them since August when my car broke down while of a road trip. I have been trying to get my parts back from them for over a month and it has been very stressful and difficult to get in touch with them. At one point they had some of my broken parts and now I call and they can\'t find them. I need these parts to return to get a refund. Today, I finally called for the 3rd time within the last three days and talked with the service department. I am so upset that they can\'t find the parts they at one point had. Plus, they aren\'t all the broken parts I needed anyways. I really hope to rectify the situation.\nMy review for now is AVOID THEM at all costs. The car works really well, but EVERYTHING else has been a hassle. I have been calling the dealership so often for over a month. I cannot believe they lost whatever parts they had. I thought they had to keep my broken parts for 2 days, but I learned from them that they do not have to. All is not horrible because that would be rude of me. My car was fixed and better than the first time. But just avoid them. I will change my review if anything changes. AVOID THEM!!! DO IT! DON\'T GO TO THEM. AVOID AVOID AVOID AVOID. But this all can change, I hope :) Thank you for your time everyone.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Novi, MI',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Laura'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 4.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 8,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Aug 13, 2015',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'We had a faulty spring we didn\'t know about before we purchased. They refuse to correct the problem, even though we purchased the extended warranty. We were told \'that\'s why we encourage customers to inspect the vehicle before they purchase.\' They did not make this recommendation. And we are not car experts as the PEOPLE WHO SELL AND SERVICE CARS should be. DO NOT BUY HERE.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Owasso, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Jamie'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': 'Aug 3, 2015',
    //                 'customer_response_text': 'Since the review I wrote 10 days ago (which was just published) the GM Mark ** for Joe Cooper called me last week and explained his sincere apology for all the problems with the 2007 Explorer Sport Trac. That truck should have never left the company that does the detailing and inspections on all their vehicles, let alone leave their dealership. Mr ** said they will make right all the mechanical expenses we had to pay for.\nI sent him the bill we had to pay for from our mechanic and the overage towing bill that State Farm would not pay. State Farm says they will pay to tow it to the nearest repair center. That would have been to Shawnee from where we were on the Turner Turnpike. State Farm expects you to pay your insurance on time. It\'s your job to get them to pay.\nGood Luck! Mr ** was was very courteous and professional. I guess it never got up the line to him the problems we were having from day one. Since it came to his attention, it got handled quickly.',
    //                 'helpful': 13,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'July 15, 2015',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'We bought a 2007 Ford Explorer Trac from Joe Cooper Ford in Shawnee. Had problems before we got back to Owasso. Got up the next day and found no anti-freeze in the radiator with the radiator cap stuck on full of stop leak. Took it to a place I have dealt with for 30 yrs to have the radiator flushed, new tires. The shop called and was told the tensioner pulley was bad - that was the noise that started before we got home. The radiator had a 8\' crack in it and had to replace it along with the serpentine belt which had some kind of engine shine fluid all over it. So $1600.00 dollars later, we thought it was fixed.\nWe started South the next day to her Dad\'s in Warr Acres OKC for the 4th and made it 6 miles West of the Wellston exit and it shelled out all the anti-freeze. Was towed to the Dealership in Shawnee. That cost $174.00 in which State Farm will only pay $61.00. Thermostat housing cracked and after another $499.00. Thank goodness for the 3yr/36,000 extra warranty. We still had to pay $100.00 deductible. Still the expense of 3 trips to Shawnee from Owasso. Ask about getting the door code from them, was told we will call you back. When pigs fly. Also told from the manager he was trying to get us reimbursed for the out of pocket cost on the truck. That was 2 weeks ago.\nThey knew it had been wrecked. It was suppose to been through a multiple point inspection and detail. Yea Right! Joe Cooper and other Dealerships spend millions of advertising dollars enticing you to come to their dealerships. It\'s too bad they don\'t spend some of the money making sure their cars are safe, reliable for the people that work hard for their living that need a vehicle, instead of talking among their sales staff when you pull up and saying \'well we got another sucker coming in\'. Thank God for social media. hang on, the fun is about to take place.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Owasso, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Rick'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 5.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 11,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'July 4, 2015',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I took my truck in for service. I could see that they were busy and I offered to come back at another time. I was told it would be a couple of hours so they would take me home. I left my truck. This was where I made my mistake. A lot of promises were made and I was informed that I wouldn\'t get my only means of transportation back for four days. I am very unhappy this time and rethinking my decision of ever using this company again. On a good note the employees were doing their best in a bad situation and were taking the brunt of customers\' dissatisfaction. The company is at fault here not the employees. After all they only follow company procedure and protocol.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Shawnee, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'anita'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': null,
    //                 'company_response_text': null,
    //                 'customer_response_date': null,
    //                 'customer_response_text': null,
    //                 'helpful': 18,
    //                 'id': 4127222,
    //                 'is_verified': false,
    //                 'original_review_date': 'Feb 15, 2015',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'Purchased a Dodge Durango. We traded in our Loaded Tahoe. Agreed on trade-in price but they didn\'t pay the entire agreed price to lender. We signed 5 different contract over a 3 month span. No one would answer me directly but refer to our situation like baking cookies! Insulting. We agreed on a downpayment but by end had to pay additional thousand dollars. They never fixed my windshield that leaks air as they promised, never fixed the stuck forward button as promised. TO THIS DAY I STILL DON\'T HAVE A TITLE! THAT WAS IN JULY OF \'14. THEY ARE ALL CROOKS!...LIARS, AND ABSOLUTELY NEED TO BE SHUT DOWN. MY COUSIN HAD SAME EXPERIENCE.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Stillwater, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': false,
    //                     'name': 'tony'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': false
    //             },
    //             {
    //                 'company_response_date': 'Aug 3, 2015',
    //                 'company_response_text': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam, odit qui vel exercitationem possimus tempora temporibus provident maxime cumque quisquam nam suscipit. Aperiam recusandae placeat obcaecati, ut distinctio in quidem!',
    //                 'customer_response_date': 'Aug 3, 2015',
    //                 'customer_response_text': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam, odit qui vel exercitationem possimus tempora temporibus provident maxime cumque quisquam nam suscipit. Aperiam recusandae placeat obcaecati, ut distinctio in quidem!',
    //                 'helpful': 26,
    //                 'id': 4127222,
    //                 'is_verified': true,
    //                 'original_review_date': 'Aug 27, 2014',
    //                 'original_stars': null,
    //                 'resolution_in_progress': false,
    //                 'review': 'I don\'t even think Joe Cooper is worth 1 star. Purchasing a truck from Joe Cooper in Yukon has turned out to be one of the worst experiences I have ever had to go through. My husband chose a truck and we had our bank approve us for the loan. The only thing Joe Cooper had to handle was the paperwork. Two months later the paperwork is still messed up. We have had to sign the paperwork 5, yes I said FIVE TIMES, and they have LOST it all FIVE times. So we have a truck we have been driving for 2 months that our bank can\'t wire money for because we don\'t have the paperwork. Where is the paperwork with all of my personal information????? Yikes, after FIVE TIMES I would think they would get it right.\nWe have called EVERYDAY about the paperwork and title and someone always says they will call us back. NEVER has anyone Ever called us back. We have always had to call them. Joe Cooper keeps giving us a temp tag and promising us paperwork but as of today we still have not seen it. We got this truck June 18th, 3 temp tags later and still no paperwork. Joe Cooper has the WORST customer service I have EVER had to deal with. I finally called the acting General Manager ** and was basically told he would look into yet again and then he hung up on me. (I would think from embarrassment from yet again not having answers for me.)\nI am pretty sure that Joe Cooper continuously giving temp tags on a 2 month old truck is not the best business practice. My next step is to file a claim with the Oklahoma Attorney Generals Office and the Better Business Bureau. I would not recommend anyone doing business with Joe Cooper in Yukon. There are so many other Ford dealers in Oklahoma that has better customer service and business practices. I cringe at the thought of Joe Cooper even being in business.',
    //                 'review_id': 4127222,
    //                 'reviewer': {
    //                     'from': 'Oklahoma City, OK',
    //                     'image_url': null,
    //                     'is_verified_buyer': false,
    //                     'is_verified_reviewer': true,
    //                     'name': 'Destiny'
    //                 },
    //                 'reviewer_image': null,
    //                 'stars': 1.0,
    //                 'verified_buyer': false,
    //                 'verified_reviewer': true
    //             }
    //         ],
    //         'total_reviews': 35
    //     });
    //     /* tslint:enable */
    // }

}
